projects:
  CharacterAPI:
    schemaPath: src/api/character-api/graphql/schema.json
    includes:
      - src/api/character-api/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/character-api/api.ts
        docsFilePath: src/api/character-api/graphql
extensions:
  amplify:
    version: 3
